### ISSUE TITLE
Could you share your multimodal dataset？

### ISSUE THREAD

**Issue by CelesteGG** [Henry1iu/ierg5350_rl_course_project#3]
I am a beginner in multimodal reinforcement learning，so it is a little hard for me to understand the  structure of your multimodal dataset through your code. It will be kind of you if you could share the contents under the folder ''/home/jb/projects/Code/IERG5350/project/ierg5350_rl_course_project/multimodal/dataset/simulation_data‘’？ You can share them on Github or send it to my e-mail：CelesteGG@mail.nwpu.edu.cn. Thank you very much!

**Comment by Henry1iu** [comment]
Hi,

Please refer to the [original implementation](https://github.com/stanford-iprl-lab/multimodal_representation) for this dataset.
